### PR TITLE
New protections

### PR DESCRIPTION
**Pull request by developer-variety**
## New Protections
* Module Flood - flood the module.cctor
* Stack Underflow - add code in front of methods causing some decompilers to crash
* HoLLy - fake obfuscator attributes, anti-watermark, memory protections

## Other
* Added JetBrains Rider to `.gitignore`
* `Confuser.Protections` requires C# `7.1` and `Allow unsafe code` for `Confuser.Protections.HoLLy`.

### CODE REVIEW

**Comment by XenocodeRCE** [comment]
@developer-variety please make a separate PR for each added protections. If PR cause runtime issue it will be too much work to fix master branch

**Comment by XenocodeRCE** [comment]
Or at least separate in different commit

**Comment by developer-variety** [comment]
Understandable, but I've made one commit to my fork for these protections. These protections are working without any issues as I've tested them myself numerous and countless times.

**Comment by XenocodeRCE** [comment]
- Stack Underflow -> Does nothing relevent, and is not preventing decompilers at all.
- Module Flood -> Won't merge, too easy to remove and it's not obfuscation its raw junk code.
- HoLLy -> **Fake obfuscators** is something I consider adding, **anti-watermark** removes the ConfuserEx watermark, thats a big no, **memory protections** might have issue with threading.

@developer-variety you told me you tested it ?

**Comment by developer-variety** [comment]
@XenocodeRCE Yes, I have tested these protections countless times.

**Pull request closed without merging**
